-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 13:54:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shelfdiver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shelfdiver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shelfdiver` DEFAULT CHARACTER SET utf8mb4 ;
USE `shelfdiver` ;

-- -----------------------------------------------------
-- Table `shelfdiver`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`users` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(50) NULL,
  `lastname` VARCHAR(50) NULL,
  `role` VARCHAR(15) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`products` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `view_count` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shelfdiver`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`type_of_properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`type_of_properties` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`type_of_properties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `property_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`properties` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`properties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `values` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `users_id` INT NOT NULL,
  `type_of_properties_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_idx` (`users_id` ASC) VISIBLE,
  INDEX `type_of_properties_idx` (`type_of_properties_id` ASC) VISIBLE,
  CONSTRAINT `fk_properties_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shelfdiver`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_properties_type_of_properties1`
    FOREIGN KEY (`type_of_properties_id`)
    REFERENCES `shelfdiver`.`type_of_properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`type_of_filters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`type_of_filters` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`type_of_filters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `filter_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`filters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`filters` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`filters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `users_id` INT NOT NULL,
  `type_of_filters_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_idx` (`users_id` ASC) VISIBLE,
  INDEX `type_of_filters_idx` (`type_of_filters_id` ASC) VISIBLE,
  CONSTRAINT `fk_filters_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shelfdiver`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filters_type_of_filters1`
    FOREIGN KEY (`type_of_filters_id`)
    REFERENCES `shelfdiver`.`type_of_filters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`products_has_properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`products_has_properties` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`products_has_properties` (
  `products_id` INT NOT NULL,
  `properties_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `properties_id`),
  INDEX `properties_idx` (`properties_id` ASC) VISIBLE,
  INDEX `products_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_properties_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `shelfdiver`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_properties_properties1`
    FOREIGN KEY (`properties_id`)
    REFERENCES `shelfdiver`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`properties_has_filters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`properties_has_filters` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`properties_has_filters` (
  `properties_id` INT NOT NULL,
  `filters_id` INT NOT NULL,
  PRIMARY KEY (`properties_id`, `filters_id`),
  INDEX `filters_idx` (`filters_id` ASC) VISIBLE,
  INDEX `properties_idx` (`properties_id` ASC) VISIBLE,
  CONSTRAINT `fk_properties_has_filters_properties1`
    FOREIGN KEY (`properties_id`)
    REFERENCES `shelfdiver`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_properties_has_filters_filters1`
    FOREIGN KEY (`filters_id`)
    REFERENCES `shelfdiver`.`filters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shelfdiver`.`app_assets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shelfdiver`.`app_assets` ;

CREATE TABLE IF NOT EXISTS `shelfdiver`.`app_assets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_logo` VARCHAR(255) NULL,
  `app_text` TEXT NULL,
  `app_icon` VARCHAR(255) NULL,
  `app_color` VARCHAR(45) NULL,
  `app_background` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
